<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Title");
?>Text here....<?$APPLICATION->IncludeComponent(
	"api:feedbackex", 
	"uikit", 
	array(
		"API_FEX_FORM_ID" => "FORM7",
		"BCC" => "",
		"COLOR" => "default",
		"DATETIME" => "",
		"DIR_URL" => "",
		"DISABLE_SEND_MAIL" => "N",
		"DISPLAY_FIELDS" => array(
			0 => "NAME",
			1 => "PHONE",
			2 => "MESSAGE",
		),
		"EMAIL_ERROR_MESS" => "Указанный E-mail некорректен",
		"EMAIL_TO" => "",
		"FIELD_ERROR_MESS" => "#FIELD_NAME# обязательное",
		"FIELD_NAME_POSITION" => "stacked",
		"FIELD_SIZE" => "default",
		"FORM_AUTOCOMPLETE" => "Y",
		"FORM_CLASS" => "",
		"FORM_FIELD_WIDTH" => "",
		"FORM_LABEL_TEXT_ALIGN" => "left",
		"FORM_LABEL_WIDTH" => "150px",
		"FORM_SUBMIT_CLASS" => "uk-button uk-width-1-1",
		"FORM_SUBMIT_STYLE" => "",
		"FORM_SUBMIT_VALUE" => "Отправить",
		"FORM_TEXTAREA_ROWS" => "5",
		"FORM_TITLE" => "Обратная связь",
		"FORM_TITLE_LEVEL" => "3",
		"FORM_WIDTH" => "",
		"HIDE_ASTERISK" => "N",
		"HIDE_FIELD_NAME" => "N",
		"MAIL_SEND_USER" => "N",
		"MAIL_SUBJECT_ADMIN" => "#SITE_NAME#: Сообщение из формы обратной связи",
		"MAIL_SUBJECT_USER" => "#SITE_NAME#: Копия сообщения из формы обратной связи",
		"OK_TEXT" => "Сообщение успешно отправлено",
		"OK_TEXT_AFTER" => "Спасибо! Мы рассмотрим сообщение и обязательно свяжемся с Вами.<br>Пожалуйста, дождитесь ответа.",
		"PAGE_TITLE" => "",
		"PAGE_URL" => "",
		"REPLACE_FIELD_FROM" => "Y",
		"REQUIRED_FIELDS" => array(
			0 => "PHONE",
		),
		"SCROLL_SPEED" => "1000",
		"THEME" => "gradient",
		"TITLE_DISPLAY" => "N",
		"USE_AUTOSIZE" => "Y",
		"USE_JQUERY" => "N",
		"USE_MODAL" => "Y",
		"USE_PLACEHOLDER" => "Y",
		"USE_SCROLL" => "Y",
		"WRITE_MESS_DIV_STYLE" => "padding:10px;border-bottom:1px dashed #dadada;",
		"WRITE_MESS_DIV_STYLE_NAME" => "font-weight:bold;",
		"WRITE_MESS_DIV_STYLE_VALUE" => "",
		"WRITE_MESS_FILDES_TABLE" => "N",
		"WRITE_MESS_TABLE_STYLE" => "border-collapse: collapse; border-spacing: 0;",
		"WRITE_MESS_TABLE_STYLE_NAME" => "max-width: 200px; color: #848484; vertical-align: middle; padding: 5px 30px 5px 0px; border-bottom: 1px solid #e0e0e0; border-top: 1px solid #e0e0e0;",
		"WRITE_MESS_TABLE_STYLE_VALUE" => "vertical-align: middle; padding: 5px 30px 5px 0px; border-bottom: 1px solid #e0e0e0; border-top: 1px solid #e0e0e0;",
		"COMPONENT_TEMPLATE" => "uikit",
		"MODAL_ID" => "#API_FEX_MODAL_FORM7",
		"MODAL_BTN_TEXT" => "Обратная связь",
		"MODAL_BTN_CLASS" => "api_button",
		"MODAL_BTN_ID" => "",
		"MODAL_BTN_SPAN_CLASS" => "api_icon",
		"MODAL_HEADER_TEXT" => "Обратная связь",
		"MODAL_FOOTER_TEXT" => ""
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>