<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
/** @var array $arParams */
/** @var array $arResult */
/** @global CMain $APPLICATION */
/** @global CUser $USER */
/** @global CDatabase $DB */
/** @var CBitrixComponentTemplate $this */
/** @var string $templateName */
/** @var string $templateFile */
/** @var string $templateFolder */
/** @var string $componentPath */
/** @var CBitrixComponent $component */

$this->addExternalCss("/bitrix/css/main/bootstrap.css");

if($arParams["USE_COMPARE"]=="Y")
{
	?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.compare.list",
	"",
	array(
		"IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
		"IBLOCK_ID" => $arParams["IBLOCK_ID"],
		"NAME" => $arParams["COMPARE_NAME"],
		"DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["element"],
		"COMPARE_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["compare"],
	),
	$component,
	array("HIDE_ICONS" => "Y")
);?><?
}
if (isset($arParams['USE_COMMON_SETTINGS_BASKET_POPUP']) && $arParams['USE_COMMON_SETTINGS_BASKET_POPUP'] == 'Y')
{
	$basketAction = (isset($arParams['COMMON_ADD_TO_BASKET_ACTION']) ? $arParams['COMMON_ADD_TO_BASKET_ACTION'] : '');
}
else
{
	$basketAction = (isset($arParams['SECTION_ADD_TO_BASKET_ACTION']) ? $arParams['SECTION_ADD_TO_BASKET_ACTION'] : '');
}
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.search",
	"",
	Array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "N",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "9",
		"IBLOCK_TYPE" => "1c_catalog",
		"LINE_ELEMENT_COUNT" => "3",
		"NO_WORD_LOGIC" => "N",
		"OFFERS_CART_PROPERTIES" => array("CML2_LINK","_KHARAKTERISTIKI_NOMENKLATURY","AMORTIZATR","AMORTIZATR_1","KOLLICHESTVO_KOLES","BAGAZHNIK","MATERIAL","BREND","VAZHNAYA_INFORMATSIYA_PO_TOVARAM","VAYVAYVA","VES","VILKA_PEREDNYAYA","DIAMETR_KOLES","RAZMER_GOLOVNOGO_UBORA","VOZRASTNAYA_GRUPPA","VTULKA_ZADNYAYA","DIAMETR_KOLESA","RAZMER_OBUVI","CML2_ARTICLE","CML2_BASE_UNIT","VID_DEYATELNOSTI","VTULKA_PEREDNYAYA","CML2_MANUFACTURER","RAZMER_PERCHATOK","CML2_TRAITS","CML2_TAXES","CML2_ATTRIBUTES","CML2_BAR_CODE","VTORAYA","DLINA","MAKSIMALNAYA_NAGRUZKA_VES_POLZOVATELYA","SEZON","VYSOTA","GEOMETRIYA","DETSKIY_RAZMER","ZADNIY_PEREKLYUCHATEL_SKOROSTEY","SOOTVETSTVUET_RAZMERU","DIAMETR_VKLADYSHA","DOP_MENEDZHER","ZVYEZDOCHKA","DIAMETR","DLINA_PALOK","DRUGIE_POSTAVSHCHIKI","KARETKA","DLYA_TARELKI","ZHESTKOST_KOLESA","INFORMATSIYA_O_MAGAZINE","KASSETA_TRESHCHOTKA","LEVAYA_PRAVAYA","PRIORITET","KOLICHESTVO_KAMER","KOLICHESTVO_SKOROSTEY","MOSHCHNOST","DLINA_1","ISPOLZOVANIE","KOLLICHESTVO_PROGRAMM","KOLICHESTVO","KRYLYA","MATERIAL_KOLESA","DLINA_2","KARKAS","MATERIAL_RAMY","OBODA","OBOROTY","MAKSIMALNYY_UROVEN_VODY","PEDALI","PREDZAKAZY","RAZMER_GETR","KUPOL","PEREDNIY_PEREKLYUCHATEL_SKOROSTEY","RAZMER_GIMN_MYACHEY","PLOSHCHAD_GRAVIROVANNOY_TABLICHKI","POKRYSHKI","POL","RAZMER_OLD","RAZMER","RAZMER_3","TIP_TOVARA","FORMA","NAGRUZKA","PROIZVODITELNOST_NASOSA","RAZMER_RAMY","RULEVAYA_KOLONKA","RAZMER_PLAKETKI","SEDLO","SISTEMA","USLOVIYA_RABOTY_1","RAZMER_FORMY","TORMOZA","RAZMER_FUTBOLKI","ROST","UPRAVLENIE_SKOROSTYU_I_NAKLONOM_NA_PORUCHNYAKH","PROVERKA_PROVERKI","RAZMER_FUTLYARA","UPAKOVKA","TSVET","USLOVIYA_PO_DOSTAVKE","TSVET_1","TSENOOBRAZOVANIE","USLOVIYA_RABOTY","TSVET_2","SHIFTERY","TIP","RISUNOK","TSVET_GRAVIROVKI","TIP_1"),
		"OFFERS_FIELD_CODE" => array("",""),
		"OFFERS_LIMIT" => "5",
		"OFFERS_PROPERTY_CODE" => array("CML2_LINK","_KHARAKTERISTIKI_NOMENKLATURY","AMORTIZATR","AMORTIZATR_1","KOLLICHESTVO_KOLES","BAGAZHNIK","MATERIAL","BREND","VAZHNAYA_INFORMATSIYA_PO_TOVARAM","VAYVAYVA","VES","VILKA_PEREDNYAYA","DIAMETR_KOLES","RAZMER_GOLOVNOGO_UBORA","VOZRASTNAYA_GRUPPA","VTULKA_ZADNYAYA","DIAMETR_KOLESA","RAZMER_OBUVI","CML2_ARTICLE","CML2_BASE_UNIT","VID_DEYATELNOSTI","VTULKA_PEREDNYAYA","CML2_MANUFACTURER","RAZMER_PERCHATOK","CML2_TRAITS","CML2_TAXES","CML2_ATTRIBUTES","CML2_BAR_CODE","VTORAYA","DLINA","MAKSIMALNAYA_NAGRUZKA_VES_POLZOVATELYA","SEZON","VYSOTA","GEOMETRIYA","DETSKIY_RAZMER","ZADNIY_PEREKLYUCHATEL_SKOROSTEY","SOOTVETSTVUET_RAZMERU","DIAMETR_VKLADYSHA","DOP_MENEDZHER","ZVYEZDOCHKA","DIAMETR","DLINA_PALOK","DRUGIE_POSTAVSHCHIKI","KARETKA","DLYA_TARELKI","ZHESTKOST_KOLESA","INFORMATSIYA_O_MAGAZINE","KASSETA_TRESHCHOTKA","LEVAYA_PRAVAYA","PRIORITET","KOLICHESTVO_KAMER","KOLICHESTVO_SKOROSTEY","MOSHCHNOST","DLINA_1","ISPOLZOVANIE","KOLLICHESTVO_PROGRAMM","KOLICHESTVO","KRYLYA","MATERIAL_KOLESA","DLINA_2","KARKAS","MATERIAL_RAMY","OBODA","OBOROTY","MAKSIMALNYY_UROVEN_VODY","PEDALI","PREDZAKAZY","RAZMER_GETR","KUPOL","PEREDNIY_PEREKLYUCHATEL_SKOROSTEY","RAZMER_GIMN_MYACHEY","PLOSHCHAD_GRAVIROVANNOY_TABLICHKI","POKRYSHKI","POL","RAZMER_OLD","RAZMER","RAZMER_3","TIP_TOVARA","FORMA","NAGRUZKA","PROIZVODITELNOST_NASOSA","RAZMER_RAMY","RULEVAYA_KOLONKA","RAZMER_PLAKETKI","SEDLO","SISTEMA","USLOVIYA_RABOTY_1","RAZMER_FORMY","TORMOZA","RAZMER_FUTBOLKI","ROST","UPRAVLENIE_SKOROSTYU_I_NAKLONOM_NA_PORUCHNYAKH","PROVERKA_PROVERKI","RAZMER_FUTLYARA","UPAKOVKA","TSVET","USLOVIYA_PO_DOSTAVKE","TSVET_1","TSENOOBRAZOVANIE","USLOVIYA_RABOTY","TSVET_2","SHIFTERY","TIP","RISUNOK","TSVET_GRAVIROVKI","TIP_1",""),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "sp07restail",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PRICE_CODE" => array("Для сайта (САЙТ цена)"),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array("_KHARAKTERISTIKI_NOMENKLATURY","LSD_DISPLEY","AMORTIZATR","AMORTIZATR_1","GLUBINA","BAGAZHNIK","VES_1","VYSOTA_FIGUR","DIAMETR_GORLYSHKA","BREND","VES","VILKA_PEREDNYAYA","GUBKA","ZASHCHITA_OT_ULTROFIOLETA","VAZHNAYA_INFORMATSIYA_PO_TOVARAM","VAYVAYVA","VOZRASTNAYA_GRUPPA","VTULKA_ZADNYAYA","DEKA","ZAGIB","KOLICHESTVO_SLOEV","BLOG_POST_ID","M_SALE","CML2_ARTICLE","CML2_BASE_UNIT","VTULKA_PEREDNYAYA","DIAMETR_1","BLOG_COMMENTS_CNT","vote_count","MAXIMUM_PRICE_2","MATERIAL","MINIMUM_PRICE_2","M_NEW","rating","CML2_TRAITS","M_RECOMMEND","RECOMMEND","CML2_TAXES","vote_sum","PRODUCT_OF_THE_DAY","CML2_ATTRIBUTES","M_HIT","CML2_BAR_CODE","VID_DEYATELNOSTI","DIAMETR_KOLESA","DOP_MENEDZHER","ZADNIY_PEREKLYUCHATEL_SKOROSTEY","MATERIAL_VERKHA","VTORAYA","DLINA_2","DLINA_LOPASTI","ZVYEZDOCHKA","KOLLICHESTVO_KOLES","KOLLICHESTVO_MASSAZHNYKH_ELEMENTOV","MATERIAL_KOLBY","VYSOTA","DETSKIY_RAZMER","DRUGIE_POSTAVSHCHIKI","ZASHCHITA_BOLSHOGO_PALTSA","KARETKA","KOMPLEKTATSIYA","MATERIAL_KORPUSA","DIAMETR_VKLADYSHA","ZHESTKOST_KOLESA","ZASHCHITA_SHCHIKOLOTKI_AKHILLOVA_SUKHOZHILIYA","KASSETA_TRESHCHOTKA","KONTROL","MATERIAL_LOPASTI","MODEL_YANDEKS","DATE_TO_OFFER","DIAMETR","DLYA_TARELKI","KOLICHESTVO_KAMER","KOLICHESTVO_SKOROSTEY","LEZVIE","MATERIAL_OPRAVY","INFORMATSIYA_O_MAGAZINE","KOLLICHESTVO_PROGRAMM","MANZHETA","MATERIAL_PODKLADKI","DLINA","ISPOLZOVANIE","KOLICHESTVO_KOLES","KRYLYA","MATERIAL_LYZH","MATERIAL_PODOSHVY","KOLICHESTVO","KOLICHESTVO_PRUZHIN","MATERIAL_NAKONECHNIKA","MOSHCHNOST","OBODA","KARKAS","KOLLICHESTVO_LINZ","MAKSIMALNYY_UROVEN_VODY","MATERIAL_NIZA","NAPRYAZHENIE","PEDALI","DLINA_1","KOLLICHESTVO_PANELEY","MATERIAL_PODSHLEMNIKA","OBEM","PEREDNIY_PEREKLYUCHATEL_SKOROSTEY","KOLLICHESTVO_SHIPOV","KUPOL","MATERIAL_KOLESA","MATERIAL_RUCHKI","PLOTNOST_MATERIALA_BRYUK","POKRYSHKI","KREPLENIE_K_MASKE","MATERIAL_RAMY","MATERIAL_SIDENYA","PLOTNOST_MATERIALA_KURTKI","POL","KRYUK","MYS","OBOROTY","PLOSHCHAD_GRAVIROVANNOY_TABLICHKI","PODVESNAYA_SISTEMA","RAZMER","NAKLADKA","RAZMER_3","SKOROST","MAKSIMALNAYA_NAGRUZKA_VES_POLZOVATELYA","NALICHIE_ZAVODSKOY_ZATOCHKI","NALICHIE_KONTEYNEROV","PREDZAKAZY","PROIZVODITELNOST_NASOSA","RAZMER_RAMY","SPOSOB_KREPLENIYA_K_RUKE","MATERIAL_KAMERY","OSOBENNOSTI","RULEVAYA_KOLONKA","SSHIVKA","MATERIAL_LADONI","NAGRUZKA","OTDELENIE_DLYA_FISHEK","SEDLO","SEZON","TIP_LAP","USLOVIYA_RABOTY_1","MATERIAL_LINZ","PODNOZHKA","PRIORITET","SISTEMA","TIP_PERENOSITSY","TSENOOBRAZOVANIE","MATERIAL_OBTYURATORA","RAZMER_PLAKETKI","TIP_POKRYTIYA","TORMOZA","MATERIAL_TRUBKI","ROST","TIP_SHLEMA","UPRAVLENIE_SKOROSTYU_I_NAKLONOM_NA_PORUCHNYAKH","MATERIAL_CHULKA","RAZDVIZHNOY_MEKHANIZM","RAZMER_FORMY","UPAKOVKA","FIKSATOR_BOLSHOGO_PALTSA","MISHEN","RAZMER_FUTBOLKI","FIKSATOR_ZAPYASTYA","NAKLON","POISKOVAYA_FRAZA_3","POLOZYA","PROVERKA_PROVERKI","RAZMER_FUTLYARA","TSVET","TSVET_2","NALICHIE_VOLNOOTBOYNIKA","POISKOVAYA_FRAZA_4","RAZMER_DEKI","SHIRINA","SHIFTERY","NALICHIE_PRODUVOCHNOGO_KLAPANA","POISKOVYE_FRAZY","RAZMER_SIDENYA","STRANA_PROIZVODITEL","TIP_TOVARA","USLOVIYA_PO_DOSTAVKE","NAPOLNITEL","POISKOVYE_FRAZY_2","RAZMER_SPINKI","USLOVIYA_RABOTY","OSNOVANIE","RISUNOK_1","TIP_KOLESA","PODVESKA","PODSHIPNIK","RISUNOK","SISTEMA_NASECHEK","TIP","PRODOLNO_POPERECHNAYA_PROSHIVKA","SOSTAV","RAZMER_V_SBORE","TEMLYAK","RAZMER_KAMERY","TIP_KAMERY","REGULIROVKA_RAZMERA","TIP_KREPLENIYA","TIP_LEZVIYA","SOPROTIVLENIE","TIP_PITANIYA","STIL","TRANSPORTNYE_KOLESIKI","TSVET_GRAVIROVKI","STIL_KATANIYA","CHEKHOL_DLYA_NOG","SHIRINA_POLOZA","TARGET","TIP_1","TIP_LADONI","TOLSHCHINA","UROVEN_IGRY",""),
		"RESTART" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SHOW_PRICE_COUNT" => "1",
		"USE_LANGUAGE_GUESS" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N"
	),
	$component,
	array("HIDE_ICONS" => "Y")
);
unset($basketAction);
?>